version: '3'
services:
  dev_db:
    image: postgres:11.3-alpine
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    environment:
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
