site_name: koil
theme:
  name: material
repo_url: https://github.com/HappyValleyIO/koil
site_description: Documentation for the koil JVM SAAS starter.
site_author: Happy Valley IO - https://www.happyvalley.io
markdown_extensions:
  - codehilite
